server:
  port: 18080
spring:
  application:
    name: UCD_Parcel_Backend_Entry
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ucd_parcel?useAffectedRows=true
    username: root
    password:
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB